### ISSUE TITLE
Commas and semi-colons look upside down

### ISSUE THREAD

**Issue by kuzunguka** [mimbrown/render#101]
Is this normal in Urdu?  Just wondering. The semi-colons especially look weird!  See for example, the semi-colons in the scripture references on the last line of the 2nd section of the debaacha of Mark.

**Comment by socvid** [comment]
This is normal.  Look at your keyboard in your phone or in your kid's Urdu books.

**Comment by mnjames** [comment]
I think this is standard punctuation. This issue could be re-opened if @socvid and I are missing something and @kuzunguka is saying there's something else wrong.
