### ISSUE TITLE
Awkward line break

### ISSUE THREAD

**Issue by kuzunguka** [mimbrown/render#103]
I see an instance where a scripture reference is given in parentheses; all but the final closing parentheses marker and the period are on the first line, and just the closing parentheses and period are on the second line.  Like this, except I’m writing in English direction:
(22:12-13
).
Seems like we might want this one broken up at the dash.  Might be more examples elsewhere.

**Comment by mnjames** [comment]
I fixed a number of bad spaces in the data, but this is caused by something else.

The underlying code is `(<char style="xt">22‏:12‏-13</char>)`.
We need to be sure that lines cannot break between `(` and `<char style="xt">`, and also not between `</char>` and `)`.
