### ISSUE TITLE
Verse Ranges

### ISSUE THREAD

**Issue by mimbrown** [mimbrown/render#18]
Both verse numbers in a verse range should be contained in the special Arabic verse marker.

**Comment by mnjames** [comment]
<code>render</code> also needs to be able to handle the extra character that Paratext adds into verse ranges--the RTL symbol.

So the range 27‏-28 is logically 27-28, but the underlying unicode values are:
0032 0037 **200F** 002D 0032 0038
Depending on how SILE is outputting the numbers, it may be sufficient to simply delete this character in this context during the <code>preprocess.lua</code> stage. But currently this character is causing the pdf to not be created.
