### ISSUE TITLE
Running Headers

### ISSUE THREAD

**Issue by mimbrown** [mimbrown/render#19]
Running headers should be included in the output. On right pages, the header should be the name of the current book. On left pages, it should be the name of the current free translation section (as seen at the beginning of the left page).

**Comment by mnjames** [comment]
A couple of people have requested chapter and verse numbers in the header temporarily, to make checking easier. This would be low priority and only do it if it's easy. The format isn't too important--it doesn't have to be pretty. 

The new request at #6 is probably more important.

**Comment by mimbrown** [comment]
Closing for now. If we have time to put numbers in headers, shouldn't be too difficult.
