### ISSUE TITLE
Uppercase Greek

### ISSUE THREAD

**Issue by mimbrown** [mimbrown/render#22]
The greek in the interlinear should be uppercased. This should either be done via Paratext or at the creation of the Interlinear.xml file.

**Comment by mnjames** [comment]
I wrote a Python script that fixes this.

**Comment by mimbrown** [comment]
Is that script being applied at the export level? Should it be committed to the repo?

**Comment by mnjames** [comment]
I have a couple of bash scripts and a couple of python scripts that move files out of Paratext and into the \render file structure. The python scripts are elsewhere on my computer, and I don't see a lot of advantage at this point of moving them into repo. So I'd say just close this Issue at this point.

**Comment by mimbrown** [comment]
Sounds good.
