### ISSUE TITLE
Verse numbers & section titles

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#29]
This is a continuation of #16.

If a verse ends, there is a section title, and then a new verse begins, under the new system the output looks like this:
<table>
<tbody>
<tr>
<td />
<td />
<td align="right">end of verse twenty</td></tr>
<tr>
<td />
<td align="center">section title</td>
<td /></tr>
<tr>
<td />
<td />
<td align="right">beginning of verse twenty-one {20}</tr>
</tr></tbody></table>
I would expect
<table>
<tbody>
<tr>
<td />
<td />
<td align="right"> {20} end of verse twenty</td></tr>
<tr>
<td />
<td align="center">section title</td>
<td /></tr>
<tr>
<td />
<td />
<td align="right">beginning of verse twenty-one</tr>
</tr></tbody></table>

**Comment by mimbrown** [comment]
I don't see this happening anymore.
