### ISSUE TITLE
Footnotes at end of verse.

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#31]
The change which moved the footnote markers to the end of the verse did not move them quite far enough. Namely, if a verse ends in a footnote the visual order I'm getting from SILE pdfs is 'text-verse#-footnote'.

![image](https://user-images.githubusercontent.com/30174022/51165780-2b8f1f00-18c3-11e9-9bf4-ce4c4a0097bd.png)

The order ought to be 'text-footnote-verse#'.

**Comment by mimbrown** [comment]
Should be fixed.
