### ISSUE TITLE
Footnotes overlap

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#33]
This should probably be considered low-priority until after getting the new pagination engine running, and depending on whether I see the same problem coming up.

See the bottom of p.4 of the pdf to see how footnote 3 (red) and footnote 4 (blue) overlap. There are a couple of words missing from footnote 3--about the same distance as would be under the blue overlap.

[3.pdf](https://github.com/mimbrown/render/files/2759767/3.pdf)

The problematic verse can be found at lines 395-403 of the xml file (renamed as .txt).
[3.txt](https://github.com/mimbrown/render/files/2759768/3.txt)

[This comes from Acts 3.]

**Comment by mimbrown** [comment]
Closing due to the refactoring of the algorithm, let me know if this persists.
