### ISSUE TITLE
Missing end of verse

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#34]
See p.2, verse 10 Literal, where the last word and the verse marker #10 are both missing.

I've checked the data (.xml renamed as .txt) and it is correct, so the problem is in the SILE process.
[10.pdf](https://github.com/mimbrown/render/files/2801511/10.pdf)
[10.txt](https://github.com/mimbrown/render/files/2801512/10.txt)

**Comment by mnjames** [comment]
See all the attached, from REV 19. Two words are missing, which would fit in the red box on p.12, and the footnote marker and verse marker both have their numbers in the wrong spot. The underlying data looks fine and printing with a different page size makes thinks come our correctly, meaning this is probably being caused by where it happens to occur on the page.

I wonder if maybe it's due to there being space for the words, but the verse marker or footnote marker would be forced to be outside the margin or on the next line.
[19.pdf](https://github.com/mimbrown/render/files/2909468/19.pdf)
[Uploading 19.txt…]()

**Comment by mnjames** [comment]
Here's a similar example, MRK 12. The mistake is a missing full-stop (period), then " mark, then the symbol around the verse number 31. I've marked the spot with a box on p.6.
[12.pdf](https://github.com/mimbrown/render/files/2923232/12.pdf)
[12.txt](https://github.com/mimbrown/render/files/2923233/12.txt)

(Note that I temporarily changed the paper size to A4 to make printing drafts here easier).

**Comment by mnjames** [comment]
Note that in trying to re-create the error on REV 19, I wasn't able to replicate it. I think it might be caused to some extent by the position on the page. I ended up finding a copy of the 19.txt file in my backups.
[19.txt](https://github.com/mimbrown/render/files/2923237/19.txt)

To verify it's caused by the actual layout, I re-printed MRK 12 but using the actual book-size. It looked fine and nothing was missing.

**Comment by mimbrown** [comment]
Is this still an issue?

**Comment by mnjames** [comment]
I don't _think_ so.
