### ISSUE TITLE
Footnotes out of order

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#40]
For some reason footnotes are appearing out of order at the bottom of pages.

This has been observed in at least 3 chapters.

In Rev 9 (attached). Footnote 9 shows up p.7 (even though it ought to be on p.5). The 2nd line of that footnote, #9, is actually the first line of footnotes on p.5 but is unlabeled and appears unconnected to anything.
[6.pdf](https://github.com/mimbrown/render/files/2948670/6.pdf)
[6.txt](https://github.com/mimbrown/render/files/2948671/6.txt)

**Comment by mimbrown** [comment]
I identified several different bugs, so please keep letting me know if you find more issues.
