### ISSUE TITLE
Changing Page Numbers

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#45]
It would be nice if the <code>render</code> script took an optional argument which said where the pdfs should start their numbering. eg. <code>./render JHN --firstPage 124</code>

It would also be good if it determined if the first page was a right or left side page depending on whether the number was odd or even.

The reason for this is we will output the book (Gospels, Acts, Rev) in six separate chunks, but the chunks will then be combined all together in a larger document. Even the first book, Matthew, will being on page 20 or so because of introductions that come before it.

**Comment by mimbrown** [comment]
Added support for the --firstPage flag
