### ISSUE TITLE
Interlinear glosses fall too low

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#46]
The bottom of certain words in the interlinear glosses gets cut off by the green bar below it.

![image](https://user-images.githubusercontent.com/30174022/54269663-9006eb80-459f-11e9-811f-abb7df913ea9.png)

**Comment by mnjames** [comment]
I just noticed this still continues to be a problem:
![image](https://user-images.githubusercontent.com/30174022/55618048-fe118d80-57ae-11e9-9846-7e1b289754ec.png)

**Comment by mimbrown** [comment]
I added a point of daylight, it looks like plenty to me but let me know if there's still an issue.
