### ISSUE TITLE
Feature request: Crop marks

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#47]
This is low priority, but would be helpful if easily implemented.

I see SILE has a cropmarks.lua package, but I don't know how it works. It would be nice if we could print out current page (180mm x 240mm) in the middle of an A4 piece of paper. This would allow me to get a good look at font sizes and see if they could be made smaller.

**Comment by mimbrown** [comment]
Use the `-d|--debug` flag to print on A4 paper with cropmarks. For example, the following command would add the cropmarks and the frame borders: `./render JHN --chapter 1 -d cropmarks,frames`
