### ISSUE TITLE
Literal verse marker on wrong page

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#50]
Here is an example of where a verse marker occurs in the wrong place.

In the literal text, verse 4 ends on p.1 but the actual verse marker occurs on p.2 I would expect there to be at least one word of verse 4 on p.2 to accompany the verse marker.

[JHN.pdf](https://github.com/mimbrown/render/files/2971944/JHN.pdf)
[JHN.txt](https://github.com/mimbrown/render/files/2971945/JHN.txt)

**Comment by mimbrown** [comment]
I think these are going to have to be manually handled. If you put a `<break />` directly into the XML before the last word in verse 4, it will appear with its verse marker. That's the only easy way right now.

**Comment by mnjames** [comment]
Could this be fixed by having a non-breaking space between the end of the verse and the verseMark symbol? Unicode has such a character (U+00A0) and I tried adding it in place of space in https://github.com/mimbrown/render/blob/d917d64f80574749c6ae7a61a1b354412421ddfd/classes/sections.lua#L526 but that didn't work.

See pdf page 894 of https://drive.google.com/open?id=1AupBakTBaJESB1l_t2sp1jmneX-_FhnX for an example.

**Comment by mimbrown** [comment]
Good call. I ended up doing it in the preprocessing and it worked, at least in the spots I could see.

**Comment by mnjames** [comment]
I guess I read the code wrong (along with focusing on the wrong line).

We need a non-breaking space _before_ the verseMark symbol, not after. This would keep the verseMark always connected to its verse, which precedes it.

**Comment by mimbrown** [comment]
I had made those changes in the preprocessing step, and removed the non-breaking space from the `verse` renderer. Did that not fix this issue?

**Comment by mimbrown** [comment]
As far as I understand this is no longer an issue. Closing for now.
