### ISSUE TITLE
footnote followed by punctuation

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#54]
It appears that when a footnote is followed by punctuation, the punctuation is allowed to start a new line. This should not be the case.

See an example in the SSV on p.63 of the attached pdf. The same location can be found by searching for <code>داؤدؑ\<note</code> in the attached txt document.

[MAT.pdf](https://github.com/mimbrown/render/files/3028983/MAT.pdf)
[MAT.txt](https://github.com/mimbrown/render/files/3029758/MAT.txt)

**Comment by mimbrown** [comment]
This is my fault, I had added an extra space after footnote marks because they seemed to be too close to the following word otherwise. I removed that space. If they seem too close now, we can do some sort of conditional spacing.
