### ISSUE TITLE
Spacing issues

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#55]
1) The Greek is slightly too close to the border at the top. For example, on this page it is quite difficult to see the two dots above a couple of letters. I didn't make this change because I wasn't sure how the frame margins and the border interacted, and figured I might end up dropping the top of the Greek and the border at the same time (which seemed counterproductive).

2) There is usually (always?) too much space below the last line of Urdu glosses and the dividing line. It would be good of the space for that Urdu line was the same as all the lines above it (the white spaces between Greek).

![image](https://user-images.githubusercontent.com/30174022/55551518-72d3c180-56f4-11e9-8a4e-97317a55a058.png)

**Comment by mimbrown** [comment]
Changes have been made, but I'll wait for you to confirm before closing this.

**Comment by mnjames** [comment]
Thanks.
