### ISSUE TITLE
No spaces in Greek text

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#59]
There is a line (4th line of p.70) with no spaces in the Greek text. I cannot see any reason from the background data why this would happen.

[Sinaiticus.usx.txt](https://github.com/mimbrown/render/files/3083655/Sinaiticus.usx.txt)
[SSV.usx.txt](https://github.com/mimbrown/render/files/3083656/SSV.usx.txt)
[SSV_Lit.usx.txt](https://github.com/mimbrown/render/files/3083657/SSV_Lit.usx.txt)

**Comment by mnjames** [comment]
[LUK.pdf](https://github.com/mimbrown/render/files/3083729/LUK.pdf)
[Raw_Interlinear.xml.txt](https://github.com/mimbrown/render/files/3083746/Raw_Interlinear.xml.txt)

**Comment by mimbrown** [comment]
I did a fairly extensive rewrite of the interlinear functionality. I worked to fix both this issue and any inconsistency with the size of each line. I'm attaching a picture that shows the amount of daylight in the text between the edges of letters and their section boundaries (see: bottom-left for the highest and lowest points of any Greek text, top right for the highest and lowest points of any Urdu text). Does that look ok with you? Note that making each "strip" the same vertical height means there is some wasted space overall.
![Screen Shot 2019-09-05 at 1 56 28 PM](https://user-images.githubusercontent.com/8728868/64376775-42b38600-cfe6-11e9-8d1d-54fce360f816.png)

**Comment by mnjames** [comment]
These look like good sizes to me, but I'll have to look at more text before I know if 1) it looks fine in all contexts, and 2) if there are any cases where letters reach higher or lower.

I think having all white space the same size and all green spaces the same size is important. I'm not sure having all white spaces the same as all green spaces is.

I'm hoping it won't cause much wasted space, will it?

**Comment by mimbrown** [comment]
I'm guessing it will result in noticeable but not extreme differences. Maybe at some point we can do a comparison, but for now I'm happy to leave it as is.

**Comment by mnjames** [comment]
Do you have a development branch that I ought to test, or is it not to that
point yet?

--Malachi

**Comment by mimbrown** [comment]
It does now: `git fetch --all` and `git checkout I-59`.

**Comment by mnjames** [comment]
The final printout ended up being shorter than it was previously, not longer. Maybe on average the vertical spacing is smaller with your new layout.

I'm observing that the top green vertical space is not consistent. See pp. 30 and 31 for a fairly significant difference.

On. p31 there's a small indent on the 4th line of Greek because of a chapter break. I'm wondering if we should make that indent slightly larger (right now it almost looks like a mistake).

On. p48 line 6 there's a small indent which I think _is_ a mistake, and a bigger example on p.52 line 6... oh, now I see the cause. It would be nice for the Greek to always be justified on both sides, so in cases where the Greek word on the right or left margin is shorter than the gloss, I wonder if the Greek word can be right/left justified instead of centered. Usually centered is good, just not on the edges.
[MAT.pdf](https://github.com/mimbrown/render/files/3584850/MAT.pdf)

**Comment by mnjames** [comment]
The final printout ended up being shorter than it was previously, not longer. Maybe on average the vertical spacing is smaller with your new layout.

I'm observing that the top green vertical space is not consistent. See pp. 30 and 31 for a fairly significant difference.

On. p31 there's a small indent on the 4th line of Greek because of a chapter break. I'm wondering if we should make that indent slightly larger (right now it almost looks like a mistake).

On. p48 line 6 there's a small indent which I think _is_ a mistake, and a bigger example on p.52 line 6... oh, now I see the cause. It would be nice for the Greek to always be justified on both sides, so in cases where the Greek word on the right or left margin is shorter than the gloss, I wonder if the Greek word can be right/left justified instead of centered. Usually centered is good, just not on the edges.

[MAT.pdf](https://github.com/mimbrown/render/files/3584901/MAT.pdf)

Also, it appears that your fixes _does_ solve the initial problem in this issue, where the horizontal spacing was too tight.

**Comment by mimbrown** [comment]
For the vertical size difference: I'm assuming you're referencing the first green lines of pages 30 and 31? Currently the first lines are the exceptions and can be different sizes. If that's not acceptable we may need to have a conversation to define what should happen there.
As for the justification, I'm happy to do what you're asking but I guess I'm a little surprised that that's what you want. In extreme cases it looks pretty funky to me.
![Screen Shot 2019-09-06 at 4 42 08 PM](https://user-images.githubusercontent.com/8728868/64464490-60a3e800-d0c5-11e9-9f34-f77af8e713d6.png)

**Comment by mimbrown** [comment]
Closing for now without the special greek margins. Happy to add it back in if necessary.

**Comment by mnjames** [comment]
The team discussed and is happy with the current way Greek centers over the gloss and doesn't touch the margin. So no need for further revision.
