### ISSUE TITLE
Unequal white space in interlinear

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#60]
On p.73 of Luke, the 6th line of interlinear glossing runs into the green below it. This appears be be because the whitespace is actually shorter than on other lines.

In general I'm not convinced the white bar is always the same height.

I wonder if this is caused by it being the end of a verse.

This is applies to the same set of files as #59.

**Comment by mimbrown** [comment]
The whitespace in that row is definitely measurable smaller (about 3 pts I think). I'm not sure why this is happening, skipping for now.

**Comment by mimbrown** [comment]
This was because I had made the green background a fixed height, which it shouldn't have been. Now the greek line is variable height and the whitespace should stay constant. Let me know if this is bad, but it fixes the issue.
