### ISSUE TITLE
Making footnote paragraph indent

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#65]
This is low priority.

I added some support for the \fp "footnote paragraph" marker, but can't get the indent to work right.

The `document.parindent` parameter seems to have lasting effect--it changes footnotes which follow it.

The `hbox` solution helps (otherwise the footnote starts on the far right margin), but doesn't move it past the main footnote margin.

https://github.com/mimbrown/render/blob/42c04546b96bfa6b9006cf3617e43cdbd61877fb/styles/styles.sil#L25-L26

**Comment by mimbrown** [comment]
Moved the style definition to `styles.lua` for robust settings support.
