### ISSUE TITLE
Parentheses removal consequences

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#67]
We're removing all parentheses marks in the SSV text.

Almost all of the time this is the correct thing to do, but in a few cases we actually want the parentheses showing up. [[For example, we say "twenty-four (24)" and don't want the parentheses removed there.]]

Would it be possible to have double parentheses reduced to single parentheses? So that something like <code>((24))</code> would come out looking like <code>(24)</code>? Is there any better way to differentiate?

**Comment by mimbrown** [comment]
I think we should use the normal escape variable `\`, so that `(this text)` would come out as `this text` and `\(this other text\)` would come out as `(this other text)`. Using doubles would probably be fine, but there could be ambiguous cases if parentheses were nested `like in this example (with parentheses (see 24))`.

**Comment by mnjames** [comment]
The double parentheses problem only occurs once in our text, so we might just go with that and I'll tell them it has to be triple there.

The one problem I see with the \( \) idea is that escaped sequences (at least in Universal Standard Format Markers which we use in Paratext) typically use a space to indicate the end. In particular, Paratext requires a space and will mark it as an error if it doesn't have it. So we couldn't write <code>some parentheses (with some other \(parentheses inside\))</code> because of the lack of spaces.

**Comment by mnjames** [comment]
If we type `\(` into Paratext, it comes out in the usx looking like
`<char style="(" closed="false">یہ </char>`
It's a little strange that the char style closes and then a new one occurs
`<char style=")" closed="false">ذکر ہے </char>`
I don't think it would cause a problem.

A bigger deal is still going to be teaching the team to use the backslash marker in this case. I think we might be best off just using double parentheses
'like in this example (with parentheses ((see24))).`

**Comment by mimbrown** [comment]
Alright, we'll go with the double. Let me know when you have a use case for me to test against. If you have anything with the trickier scenarios then that would also be helpful.

**Comment by mnjames** [comment]
I edited Revelation to add these sorts of double parentheses marks. I've added them in 7:4-8; 11:13, 18; 14:1, 3; 15:2; 21:16, 17.

Of particular interest would be 7:5, where the 3rd line includes `((12,000))` inside of other parentheses marks, and 15:2, where `((666)))` is inside other parentheses and result in 3 closed `)`  in a row.

[Raw_Interlinear.xml.txt](https://github.com/mimbrown/render/files/3581257/Raw_Interlinear.xml.txt)
[Sinaiticus.usx.txt](https://github.com/mimbrown/render/files/3581258/Sinaiticus.usx.txt)
[SSV.usx.txt](https://github.com/mimbrown/render/files/3581259/SSV.usx.txt)
[SSV_Lit.usx.txt](https://github.com/mimbrown/render/files/3581260/SSV_Lit.usx.txt)

**Comment by mimbrown** [comment]
Done, but please note the following exception. If non-text occurs inside double-parentheses, then the closing pair will totally disappear. E.g.,
`((should still be in parentheses <char style="zeng">but there's this</char> so the final one is missing))`
will be rendered as
`(should still be in parentheses <char style="zeng">but there's this</char> so the final one is missing`
