### ISSUE TITLE
"w" style markers break chapter numbering

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#68]
If a chapter marker is immediately followed by text which starts with a "w" marker, then the chapter number occurs after the words instead of before them.

See Acts 2:1 (p.818 in print edition) for an example.

We're currently not using the "w" marker, so if there's not an easy way to deal with this inside of SILE/render, I can add regex into my import script to strip out those codes.

**Comment by mimbrown** [comment]
See fix in branch `I-68` (`git checkout I-68`). Let me know if it works.

**Comment by mnjames** [comment]
That worked.

However, I now have a similar situation where a footnote directly follows a chapter marker, and in the printout it appears before.
