### ISSUE TITLE
Sinaiticus with Paragraphs

### ISSUE THREAD

**Issue by mimbrown** [mimbrown/render#70]
The Sinaiticus data will have `para` tags in it. Need to support this.

**Comment by mimbrown** [comment]
Could I have the full 1JN set?

**Comment by mnjames** [comment]
[Raw_Interlinear.xml.txt](https://github.com/mimbrown/render/files/3644307/Raw_Interlinear.xml.txt)
[Sinaiticus.usx.txt](https://github.com/mimbrown/render/files/3644308/Sinaiticus.usx.txt)
[SSV.usx.txt](https://github.com/mimbrown/render/files/3644309/SSV.usx.txt)
[SSV_Lit.usx.txt](https://github.com/mimbrown/render/files/3644310/SSV_Lit.usx.txt)
[Lexicon.xml.txt](https://github.com/mimbrown/render/files/3644311/Lexicon.xml.txt)
