### ISSUE TITLE
Broken verse marker

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#73]
See p.403 for an example of where the verse marker (and accompanying footnote marker) get messed up.
![image](https://user-images.githubusercontent.com/30174022/64203923-2aaefb80-ce5a-11e9-834e-709613fcdc26.png)

Note that probably because of other edits to preceding verse, and thus different pagination, this is no longer an issue.
![image](https://user-images.githubusercontent.com/30174022/64204042-8b3e3880-ce5a-11e9-843a-6838c73b4294.png)

You can also see from the 2nd example that the order of quite a few pieces got messed up in the publication. 
![image](https://user-images.githubusercontent.com/30174022/64204276-0c95cb00-ce5b-11e9-9805-1e5bcdc534b8.png)

I'm not sure how we'll track this down since the error seems to have resolved itself, but it's a fairly major issue and I'm worried it will crop up in new locations.

**Comment by mnjames** [comment]
Actually, I thought we had looked at this case before. So maybe you fixed it in the code. I just can't find a record of that in the resolved issues.

**Comment by mimbrown** [comment]
I was able to reproduce this bug, and adding an extra RTL mark before the verse marker seems to have resolved it. Let me know if it comes up again.
