### ISSUE TITLE
Dictionary form of Glossary words ("w" marker)

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#74]
In MAT 2:1 the word Herod occurs in two forms. `<char style="w">ہِرودِ|ہِرود</char>`. Of those, only the first should show up in print (the second if for a future glossary lookup tool). So we'd like to show the first form and delete the second form when printing.

Note that 'first' and 'second' describe the actual underlying unicode order, but not the way they display on screen. The form we want is visually on the right (so 'first' in RTL terms).

**Comment by mimbrown** [comment]
In my copy of Matthew (which I'm sure is quite a bit older than yours), that same section looks like: `<char style="w" lemma="ہِرود">ہِرودِ</char>`, with the second form inside the lemma. If it's possible to keep that format it would be easier; otherwise, I can try to work something out.

**Comment by mnjames** [comment]
PT8 appears to output USX version 2.5, while PT9 outputs version 3.0. From what I'm getting as output, it appears that:
`<char style="w">ہِرودِ|ہِرود</char>` is USX 2.5, and
`<char style="w" lemma="ہِرود">ہِرودِ</char>` is USX 3.0

Currently only 2.5 works with ./render. However, I'd be _delighted_ if you switched over and made it compatible with 3.0 (even if it lost compatibility with 2.5). Exporting to usx is one of the only reasons I ever turn on PT8 nowadays. I've just hesitated in the past to ask you to change to USX 3.0 because I figured there were better uses of your time.

So, you can choose to update to 3.0 or to deal with the `<char style="w">ہِرودِ|ہِرود</char>` way of writing this.

**Comment by mnjames** [comment]
I'm going to 'solve' this for now by simply deleting the dictionary form. In the future, after publication of the 1st edition and once we resume work on a digital version, we can look back at this problem and try to fix it.
