### ISSUE TITLE
Problem combining chapters when using --minChapter and --maxChapter

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#77]
Note this is very, very low priority. Only work on it if there's an obvious solution.

When I run a command like `./render 1CO --minChapter 12 --maxChapter 13`, the two individual chapter files compile almost instantly but the combined file takes 10+ minutes. Also, the two individual pdfs are 6-7mb each, but the combined pdf is 367mb. It seems like running it through Ghostscript you could just use something like pdftk to stitch the two 12.pdf and 13.pdf files together.

**Comment by mimbrown** [comment]
I left those in there for backwards compatibility, but you should be able to use `--min` and `--max` instead of `--minChapter` and `--maxChapter`. Let me know if that works for you.

**Comment by mnjames** [comment]
This worked great. Thank you.
