### ISSUE TITLE
English direction in text

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#78]
In some cases English words are having their order changed. I suspect his is being caused by parentheses and brackets acting like they would in Urdu, and not as in English.

Attached is a minimal example. I've cut the rest of the text out hoping that this will help focus on the problem, but if you'd rather having the original files let me know.

The footnote on the first page ought to read like this:
'[Philo, De specialibus legibus (“On Special Laws”), 1‏.260.] (Loeb, VII, 251)]'
[1CO.pdf](https://github.com/mimbrown/render/files/3795533/1CO.pdf)
[1CO.xml.txt](https://github.com/mimbrown/render/files/3795534/1CO.xml.txt)

**Comment by mimbrown** [comment]
When I split out the English and pair it with the code points, this is what the number in the English looks like:
`1: 49
‏: 8207
.: 46
2: 50
6: 54
0: 48
.: 46`
You can see that the 1 is followed by the RTL marker `U+8207`. Is there a way to remove that?

**Comment by mnjames** [comment]
RTL markers get added automatically by PT. And I don't fully (or even partially) understand the Unicode bidi algorithm but there are places where they're definitely _supposed_ to occur.

So I don't think we can remove them from the source, but we could remove them either during my import process (I use a series of .sh scripts) or from within SILE/lua. Are you sure it will display correctly if that one marker is removed?

**Comment by mimbrown** [comment]
Malachi, do you know if this is fixed by the regex at line 57 in `importchanges.txt`?

**Comment by mnjames** [comment]
Yes, it is.
