### ISSUE TITLE
Interlinear text disappearing to the right

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#8]
In the attached files (3.xml was renamed to 3.txt for github reasons) on p.6 of the output, there is a problem in the 2nd line of interlinear. After /epigia/ there are 3 Greek words not displaying, along with their glosses. And you can see some Urdu on the right margin.

[3.pdf](https://github.com/mimbrown/render/files/2533648/3.pdf)
[3.txt](https://github.com/mimbrown/render/files/2533651/3.txt)

**Comment by mimbrown** [comment]
Closed due to new algorithm, feel free to reopen if this reoccurs.
