### ISSUE TITLE
Unnumbered footnotes

### ISSUE THREAD

**Issue by mnjames** [mimbrown/render#80]
USFM defines 3 different footnote callers:
`+` – indicates that the caller should be generated automatically by the translation editor, or publishing tools.
`-` – indicates that no caller should be generated, and is not used.
`?` – where ? represents the character to be used for the caller. The caller is defined for the specific note by the author.

Our setup is currently using `+` correctly (basically because that's the default usage and it just ignore the caller). However, we need it to start handling `-` for a specific case. The first two footnotes of REV 7 gives examples of `-` and `+` usage.
[REV.xml.txt](https://github.com/mimbrown/render/files/4193889/REV.xml.txt)

We'd like to be able to use the `-` caller and have no marking at all in the main text or in the footnote.

**Comment by mimbrown** [comment]
I guessed that the unmarked footnotes would need to line up with the other footnotes, not with the footnote numbers. If this was the wrong guess, see the comment on line 1152 in `classes/sections.lua`.
