### ISSUE TITLE
Ignore Screen Timeout

### ISSUE THREAD

**Issue by socvid** [mimbrown/render#87]
Currently while reading the app, my phone will timeout and lock according to my phones screen timeout setting.  This is distracting.  I can fit a lot of text with my high resolution screen when I zoom out and make the text small, and I use a short timeout on my phone.  The Kindle App and many of my other e-reader apps and scripture apps that I've used ignore the phone's screen timeout and will keep the phone's screen on indefinitely.  There are a few that adhere to screen timeout settings, but my observation is that the majority and the most popular ones ignore it.

**Comment by mimbrown** [comment]
I've added a plugin that should fix this, but it's hard to test, so let me know if it reoccurs.
