### ISSUE TITLE
Paragraph indent

### ISSUE THREAD

**Issue by kuzunguka** [mimbrown/render#94]
I like the new paragraph indent. Proposal: can it be increased? To my eyes it appears pretty minimal. The indent appears to be about the same amount of horizontal space occupied by just a short Urdu word such as کی.

**Comment by socvid** [comment]
I agree.  If you are going to use indents, then make it a nice size is my view!

**Comment by mnjames** [comment]
I agree. Let's try making it twice it's current size.
