### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by kuzunguka** [mimbrown/render#98]
In the main debaacha article “zer-e-nazr tarjuma o tafseer ki saakht…”, is there a typo in the word /tafseeli/ in the first sentence of this article?  Maybe it’s a variant of the word that I’m not familiar with.  I see تفیصلیwhere I would expect تفصیلی .

**Comment by mnjames** [comment]
I've raised this issue in Paratext and am waiting for feedback from the professor.
